baseURL = "https://gwbblog.top/"
languageCode = "zh-cn"
title = "Jellyfish的博客"
theme = "ananke"

[params]
  site_logo = "images/avatar.jpg"
  description = "记录学习、技术和生活"

  [params.social]
    twitter = ""

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "资源"
    url = "/links/"
    weight = 3

  [[menu.main]]
    name = "工具"
    url = "/tools/"
    weight = 4

  [[menu.main]]
    name = "游戏"
    url = "/games/"
    weight = 5

  [[menu.main]]
    name = "搜索"
    url = "/search/"
    weight = 6

  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 7
